// auth模組
export const AUTH_LOGIN = "AUTH_LOGIN";

// ui 模組
export const UI_LOADING = "UI_LOADING";
export const UI_HISTORY_MESSAGE = "UI_HISTORY_MESSAGE";
export const UI_RELOAD = "UI_RELOAD";

// todo模組
export const TODO_UPDATE_FOCUS_WORK = "TODO_UPDATE_FOCUS_WORK";
export const TODO_ADD_WORK = "TODO_ADD_WORK";
export const TODO_UPDATE_WORK_LIST = "TODO_UPDATE_WORK_LIST";
export const TODO_DELETE_WORK = "TODO_DELETE_WORK";
export const TODO_DELETE_CARD = "TODO_DELETE_CARD";
export const TODO_DELETE_TASK = "TODO_DELETE_TASK";
export const TODO_ADD_CARD = "TODO_ADD_CARD";
export const TODO_UPDATE_CARD_TITLE = "TODO_UPDATE_CARD_TITLE";
export const TODO_ADD_TASK = "TODO_ADD_TASK";
